# TCL File Generated by Component Editor 14.0
# Fri Oct 03 19:08:43 CEST 2014
# DO NOT MODIFY


# 
# avalon_demo "avalon_demo" v1.0
#  2014.10.03.19:08:43
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 13.1


# 
# module avalon_demo
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_demo
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME avalon_demo
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_demo
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file avalon_demo.vhd VHDL PATH ../../vhdl/avalon_demo/avalon_demo.vhd TOP_LEVEL_FILE
add_fileset_file debouncer.vhd VHDL PATH ../../vhdl/common/debouncer/debouncer.vhd
add_fileset_file debouncer_beh.vhd VHDL PATH ../../vhdl/common/debouncer/debouncer_beh.vhd
add_fileset_file debouncer_pkg.vhd VHDL PATH ../../vhdl/common/debouncer/debouncer_pkg.vhd
add_fileset_file sync.vhd VHDL PATH ../../vhdl/common/synchronizer/sync.vhd
add_fileset_file sync_beh.vhd VHDL PATH ../../vhdl/common/synchronizer/sync_beh.vhd
add_fileset_file sync_pkg.vhd VHDL PATH ../../vhdl/common/synchronizer/sync_pkg.vhd
add_fileset_file knightrider.vhd VHDL PATH ../../vhdl/knightrider/knightrider.vhd
add_fileset_file knightrider_beh.vhd VHDL PATH ../../vhdl/knightrider/knightrider_beh.vhd
add_fileset_file knightrider_pkg.vhd VHDL PATH ../../vhdl/knightrider/knightrider_pkg.vhd


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 32
set_parameter_property DATA_WIDTH DEFAULT_VALUE 32
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter LED_NUM INTEGER 8
set_parameter_property LED_NUM DEFAULT_VALUE 8
set_parameter_property LED_NUM DISPLAY_NAME LED_NUM
set_parameter_property LED_NUM TYPE INTEGER
set_parameter_property LED_NUM UNITS None
set_parameter_property LED_NUM HDL_PARAMETER true
add_parameter T_STEP INTEGER 25000000 ""
set_parameter_property T_STEP DEFAULT_VALUE 25000000
set_parameter_property T_STEP DISPLAY_NAME T_STEP
set_parameter_property T_STEP TYPE INTEGER
set_parameter_property T_STEP UNITS None
set_parameter_property T_STEP ALLOWED_RANGES -2147483648:2147483647
set_parameter_property T_STEP DESCRIPTION ""
set_parameter_property T_STEP HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink reset_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point control
# 
add_interface control avalon end
set_interface_property control addressUnits WORDS
set_interface_property control associatedClock clock
set_interface_property control associatedReset reset_sink
set_interface_property control bitsPerSymbol 8
set_interface_property control burstOnBurstBoundariesOnly false
set_interface_property control burstcountUnits WORDS
set_interface_property control explicitAddressSpan 0
set_interface_property control holdTime 0
set_interface_property control linewrapBursts false
set_interface_property control maximumPendingReadTransactions 0
set_interface_property control maximumPendingWriteTransactions 0
set_interface_property control readLatency 0
set_interface_property control readWaitTime 1
set_interface_property control setupTime 0
set_interface_property control timingUnits Cycles
set_interface_property control writeWaitTime 0
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control write_n write_n Input 1
add_interface_port control writedata writedata Input data_width
add_interface_port control readdata readdata Output data_width
add_interface_port control address address Input 4
set_interface_assignment control embeddedsw.configuration.isFlash 0
set_interface_assignment control embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment control embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment control embeddedsw.configuration.isPrintableDevice 0


# 
# connection point inputs
# 
add_interface inputs conduit end
set_interface_property inputs associatedClock clock
set_interface_property inputs associatedReset reset_sink
set_interface_property inputs ENABLED true
set_interface_property inputs EXPORT_OF ""
set_interface_property inputs PORT_NAME_MAP ""
set_interface_property inputs CMSIS_SVD_VARIABLES ""
set_interface_property inputs SVD_ADDRESS_GROUP ""

add_interface_port inputs button button Input 1


# 
# connection point outputs
# 
add_interface outputs conduit end
set_interface_property outputs associatedClock clock
set_interface_property outputs associatedReset reset_sink
set_interface_property outputs ENABLED true
set_interface_property outputs EXPORT_OF ""
set_interface_property outputs PORT_NAME_MAP ""
set_interface_property outputs CMSIS_SVD_VARIABLES ""
set_interface_property outputs SVD_ADDRESS_GROUP ""

add_interface_port outputs leds leds Output led_num

