# TCL File Generated by Component Editor 14.0
# Sat Jan 03 16:07:40 CET 2015
# DO NOT MODIFY


# 
# shift_ri "shift_ri" v1.0
#  2015.01.03.16:07:40
# 
# 

# 
# request TCL package from ACDS 14.0
# 
package require -exact qsys 14.0


# 
# module shift_ri
# 
set_module_property DESCRIPTION ""
set_module_property NAME shift_ri
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME shift_ri
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL shift_ri
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file shift_ri.vhd VHDL PATH ../../vhdl/instructions/shift_ri.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point nios_custom_instruction_slave
# 
add_interface nios_custom_instruction_slave nios_custom_instruction end
set_interface_property nios_custom_instruction_slave clockCycle 0
set_interface_property nios_custom_instruction_slave operands 2
set_interface_property nios_custom_instruction_slave ENABLED true
set_interface_property nios_custom_instruction_slave EXPORT_OF ""
set_interface_property nios_custom_instruction_slave PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave a dataa Input 32
add_interface_port nios_custom_instruction_slave r result Output 32


# 
# connection point nios_custom_instruction_slave_1
# 
add_interface nios_custom_instruction_slave_1 nios_custom_instruction end
set_interface_property nios_custom_instruction_slave_1 clockCycle 0
set_interface_property nios_custom_instruction_slave_1 operands 2
set_interface_property nios_custom_instruction_slave_1 ENABLED true
set_interface_property nios_custom_instruction_slave_1 EXPORT_OF ""
set_interface_property nios_custom_instruction_slave_1 PORT_NAME_MAP ""
set_interface_property nios_custom_instruction_slave_1 CMSIS_SVD_VARIABLES ""
set_interface_property nios_custom_instruction_slave_1 SVD_ADDRESS_GROUP ""

add_interface_port nios_custom_instruction_slave_1 n n Input 8

