#!/bin/bash

# the environment variables  PROJECT_NAME, QUARTUS_PROJECT_DIR and BSP_DIR  are set by the makefile which calls this script

SRC_DIR=./src

NIOS2_APP_GEN_ARGS="--elf-name ${PROJECT_NAME}.elf --set APP_CFLAGS_OPTIMIZATION -Os --set OBJDUMP_INCLUDE_SOURCE 1 --src-rdir ${SRC_DIR}"


# First, check to see if $SOPC_KIT_NIOS2 environmental variable is set.
# This variable is required for the command line tools to execute correctly.
if [ -z "${SOPC_KIT_NIOS2}" ]
then
    echo Required \$SOPC_KIT_NIOS2 Environmental Variable is not set!
    exit 1
fi



# Don't run make if create-this-app script is called with --no-make arg
SKIP_MAKE=
while [ $# -gt 0 ]
do
  case "$1" in
      --no-make)
          SKIP_MAKE=1
          ;;
  esac
  shift
done


cmd="nios2-app-generate-makefile --app-dir ${PROJECT_NAME} --bsp-dir ${BSP_DIR} --set QUARTUS_PROJECT_DIR=${QUARTUS_PROJECT_DIR} ${NIOS2_APP_GEN_ARGS}"

echo "create-this-app: Running \"${cmd}\""
$cmd || {
    echo "nios2-app-generate-makefile failed"
    exit 1
}

exit 0
