-- megafunction wizard: %FFT v14.0%
-- GENERATION: XML

-- ============================================================
-- Megafunction Name(s):
-- 			asj_fft_sglstream_fft_140
-- ============================================================
-- Generated by FFT 14.0 [Altera, IP Toolbench 1.3.0 Build 200]
-- ************************************************************
-- THIS IS A WIZARD-GENERATED FILE. DO NOT EDIT THIS FILE!
-- ************************************************************
-- Copyright (C) 1991-2014 Altera Corporation
-- Any megafunction design, and related net list (encrypted or decrypted),
-- support information, device programming or simulation file, and any other
-- associated documentation or information provided by Altera or a partner
-- under Altera's Megafunction Partnership Program may be used only to
-- program PLD devices (but not masked PLD devices) from Altera.  Any other
-- use of such megafunction design, net list, support information, device
-- programming or simulation file, or any other related documentation or
-- information is prohibited for any other purpose, including, but not
-- limited to modification, reverse engineering, de-compiling, or use with
-- any other silicon devices, unless such use is explicitly licensed under
-- a separate agreement with Altera or a megafunction partner.  Title to
-- the intellectual property, including patents, copyrights, trademarks,
-- trade secrets, or maskworks, embodied in any such megafunction design,
-- net list, support information, device programming or simulation file, or
-- any other related documentation or information provided by Altera or a
-- megafunction partner, remains with Altera, the megafunction partner, or
-- their respective licensors.  No other licenses, including any licenses
-- needed under any third party's intellectual property, are provided herein.

library IEEE;
use IEEE.std_logic_1164.all;
library fft_lib;
use fft_lib.fft_pack_fft_140.all;

ENTITY fft IS
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		inverse	: IN STD_LOGIC;
		sink_valid	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		sink_real	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_imag	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_ready	: IN STD_LOGIC;
		sink_ready	: OUT STD_LOGIC;
		source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		source_valid	: OUT STD_LOGIC;
		source_exp	: OUT STD_LOGIC_VECTOR (5 DOWNTO 0);
		source_real	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		source_imag	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0)
	);
END fft;

ARCHITECTURE SYN OF fft IS


	COMPONENT asj_fft_sglstream_fft_140
	GENERIC (
		device_family	: STRING;
		nps	: NATURAL;
		bfp	: NATURAL;
		nume	: NATURAL;
		mpr	: NATURAL;
		twr	: NATURAL;
		bpr	: NATURAL;
		bpb	: NATURAL;
		fpr	: NATURAL;
		mram	: NATURAL;
		m512	: NATURAL;
		mult_type	: NATURAL;
		mult_imp	: NATURAL;
		dsp_arch	: NATURAL;
		srr	: STRING;
		rfs1	: STRING;
		rfs2	: STRING;
		rfs3	: STRING;
		rfc1	: STRING;
		rfc2	: STRING;
		rfc3	: STRING
	);
	PORT (
		clk	: IN STD_LOGIC;
		reset_n	: IN STD_LOGIC;
		inverse	: IN STD_LOGIC;
		sink_valid	: IN STD_LOGIC;
		sink_sop	: IN STD_LOGIC;
		sink_eop	: IN STD_LOGIC;
		sink_real	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_imag	: IN STD_LOGIC_VECTOR (15 DOWNTO 0);
		sink_error	: IN STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_ready	: IN STD_LOGIC;
		sink_ready	: OUT STD_LOGIC;
		source_error	: OUT STD_LOGIC_VECTOR (1 DOWNTO 0);
		source_sop	: OUT STD_LOGIC;
		source_eop	: OUT STD_LOGIC;
		source_valid	: OUT STD_LOGIC;
		source_exp	: OUT STD_LOGIC_VECTOR (5 DOWNTO 0);
		source_real	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0);
		source_imag	: OUT STD_LOGIC_VECTOR (15 DOWNTO 0)
	);

	END COMPONENT;

BEGIN

	asj_fft_sglstream_fft_140_inst : asj_fft_sglstream_fft_140
	GENERIC MAP (
		device_family => "Cyclone IV E",
		nps => 1024,
		bfp => 1,
		nume => 1,
		mpr => 16,
		twr => 16,
		bpr => 16,
		bpb => 4,
		fpr => 4,
		mram => 0,
		m512 => 0,
		mult_type => 1,
		mult_imp => 0,
		dsp_arch => 0,
		srr => "AUTO_SHIFT_REGISTER_RECOGNITION=OFF",
		rfs1 => "fft_1n1024sin.hex",
		rfs2 => "fft_2n1024sin.hex",
		rfs3 => "fft_3n1024sin.hex",
		rfc1 => "fft_1n1024cos.hex",
		rfc2 => "fft_2n1024cos.hex",
		rfc3 => "fft_3n1024cos.hex"
	)
	PORT MAP (
		clk  =>  clk,
		reset_n  =>  reset_n,
		inverse  =>  inverse,
		sink_valid  =>  sink_valid,
		sink_sop  =>  sink_sop,
		sink_eop  =>  sink_eop,
		sink_real  =>  sink_real,
		sink_imag  =>  sink_imag,
		sink_ready  =>  sink_ready,
		sink_error  =>  sink_error,
		source_error  =>  source_error,
		source_ready  =>  source_ready,
		source_sop  =>  source_sop,
		source_eop  =>  source_eop,
		source_valid  =>  source_valid,
		source_exp  =>  source_exp,
		source_real  =>  source_real,
		source_imag  =>  source_imag
	);


END SYN;


-- =========================================================
-- FFT Wizard Data
-- ===============================
-- DO NOT EDIT FOLLOWING DATA
-- @Altera, IP Toolbench@
-- Warning: If you modify this section, FFT Wizard may not be able to reproduce your chosen configuration.
-- 
-- Retrieval info: <?xml version="1.0"?>
-- Retrieval info: <MEGACORE title="FFT MegaCore Function"  version="14.0"  build="200"  iptb_version="1.3.0 Build 200"  format_version="120" >
-- Retrieval info:  <NETLIST_SECTION class="altera.ipbu.flowbase.netlist.model.FFTModelClass"  active_core="asj_fft_sglstream_fft_140" >
-- Retrieval info:   <STATIC_SECTION>
-- Retrieval info:    <PRIVATES>
-- Retrieval info:     <NAMESPACE name = "parameterization">
-- Retrieval info:      <PRIVATE name = "use_mem" value="1"  type="BOOLEAN"  enable="1" />
-- Retrieval info:      <PRIVATE name = "mem_type" value="M512"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DEVICE" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NPS" value="1024"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MPR" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "TWR" value="16"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "OPR" value="29"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ARCH" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUME" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENGINE_THROUGHPUT" value="4"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "BFP" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MULT_TYPE" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MULT_IMP" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "MEGA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "M512" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "LOGIC_IN_RAM" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_LE" value="4952"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_M4K" value="19"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_MEGA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_M512" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_DSP" value="24"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_CALC_CYCLES" value="1024"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_BLK_THROUGHPUT_CYCLES" value="1024"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs1" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs2" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfs3" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc1" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc2" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "rfc3" value="romfile_1024.hex"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENA" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "NUM_MEMBITS" value="155648"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "INPUT_ORDER" value="1"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "OUTPUT_ORDER" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "REPRESENTATION" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "ENGINE_ONLY" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DSP_ARCH" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:      <PRIVATE name = "DIRECTION" value="0"  type="INTEGER"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen_enable">
-- Retrieval info:      <PRIVATE name = "language" value="VHDL"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "simgen">
-- Retrieval info:      <PRIVATE name = "filename" value="fft.vho"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "greybox">
-- Retrieval info:      <PRIVATE name = "filename" value="fft_syn.v"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "quartus_settings">
-- Retrieval info:      <PRIVATE name = "DEVICE" value="EP4CE115F29C7"  type="STRING"  enable="1" />
-- Retrieval info:      <PRIVATE name = "FAMILY" value="Cyclone IV E"  type="STRING"  enable="1" />
-- Retrieval info:     </NAMESPACE>
-- Retrieval info:     <NAMESPACE name = "serializer"/>
-- Retrieval info:    </PRIVATES>
-- Retrieval info:    <FILES/>
-- Retrieval info:    <PORTS/>
-- Retrieval info:    <LIBRARIES/>
-- Retrieval info:   </STATIC_SECTION>
-- Retrieval info:  </NETLIST_SECTION>
-- Retrieval info: </MEGACORE>
-- =========================================================
